name: ci

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:

  clang-mac:
    if: false
    runs-on: macos-latest

    steps:    
    - uses: actions/checkout@v4
    - run: clang --version
    - name: Build and Test Clang      
      run: |        
        cd src
        clang -DTEST -o build  build.c 
        ./build
            
  linux-gcc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: gcc --version
    - run: sudo apt install valgrind
    - name: Build and test
      run: |
        cd src
        gcc -DTEST build.c -o build
        ./build
        valgrind ./cake -DTEST -fanalyzer  token.c  hashmap.c  console.c  tokenizer.c  osstream.c  fs.c  options.c  object.c  expressions.c  pre_expressions.c  parser.c  compile.c  visit_defer.c  visit_il.c  visit_asm.c  flow.c  error.c  target.c  type.c  main.c

  windows-msvc-x86:
    if: false
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: amd64_x86
    - name: Build and test
      run: |
        cd src
        cl build.c -DTEST 
        .\build.exe

  windows-msvc-x64:
    if: false
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x64
    - name: Build and test
      run: |
        cd src
        cl build.c -DTEST 
        .\build.exe

 
