name: ci

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  linux-gcc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: gcc --version
    - name: Build and test
      run: |
        cd src
        gcc -DTEST build.c -o build
        ./build

  linux-gcc-ubuntu-prev:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - run: gcc --version
    - name: Build
      run: |
        cd src
        gcc build.c -o build
        ./build

  windows-msvc:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: amd64_x86
    - name: Build and test
      run: |
        cd src
        cl build.c -DTEST 
        .\build.exe
